### PR TITLE
Enable debug when CPU core is brought up

### PR DESCRIPTION
**Pull request by sysgo-maw**
This allows connecting to all cores through JTAG. It was possible before the switch to PSCI happened
but the relevant code got removed.

Signed-off-by: Matthias Welwarsky <maw@sysgo.com>

### CODE REVIEW

**Comment by petegriffin** [comment]
Hi,

Just for completeness, the regression mentioned in this patch was introduced in SHA 4bd2f33cf993025dc8d1b1a96a760bc876791b86.

This patch has been tested with OpenOCD, and allows the JTAG debugger to connect to all 8 cores. Although cpuidle in the kernel still needs to be disabled to maintain the debug connection.

regards,

Peter.

**Comment by daniel-thompson** [comment]
Not quite sure who "owns" this repo at present (hence the scattergun assignment) but it would definitely be good to get a review from someone in the LT.

**Comment by sysgo-maw** [comment]
The added code definitely works, but there might be a more appropriate place to put it. Also, it would be good to understand if it's intentional that cpu idle management disturbs debugging. Not only has this a major impact on an external debugger, but it might also affect Linux' use of CoreSight components for performance monitoring and tracing.

**Comment by Leo-Yan** [comment]
@petegriffin has sent one email to @hzhuang1 and me. I will verify this patch in ARM-TF on Hikey and verify if Linux kernel CPUIdle can work well or not.

@sysgo-maw, AFAIK, CPU low power state do impact the debugging logic. I say this just as a very general description, but there have some difference for different CPU variants and SoC vendors have different implementation for this. For example, from my previous experience, the SoC can support Jtag connection even CPU has been in low power states. But for most usual case, we should disable low power states so can keep debug logic is always working and Jtag can always connect with it so can work properly. In the kernel, you can quickly disable all low power states by add "nohlt" into command line.

**Comment by Leo-Yan** [comment]
Have tested this patch, it can worked well with AOSP kernel 4.4. Also checked CPUIdle, suspend/resume flows, both can work well.

@hzhuang1 Please help merge. Thanks.

**Comment by vchong** [comment]
Should this go into 96boards-hikey/arm-trusted-firmware too?

**Comment by hzhuang1** [comment]
@petegriffin We already moved the git repository into 96boards-hikey. Please submit pull request into https://github.com/96boards-hikey/arm-trusted-firmware/ on branch hikey.

Close it now.

**Pull request closed without merging**
