### PR TITLE
hikey: enable ddr 800mhz

### PR DESCRIPTION
**Pull request by koenkooi**
Make DDR working in 800MHz by default.

Signed-off-by: Haojian Zhuang haojian.zhuang@linaro.org

### CODE REVIEW

**Comment by koenkooi** [comment]
hmm, I get this after apply this patch and reflashing:

```
Switch to aarch64 mode. CPU0 executes at 0xf9801000!
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(release):be3e473
NOTICE:  BL1: Built : 16:11:14, Apr  3 2015
NOTICE:  acpu_dvfs_set_freq: set acpu freq success!INFO:    lpddr3_freq_init, set ddrc 800mhz
INFO:    init ddr3 rank0
INFO:    ddr3 rank1 init pass
INFO:    Elpida DDR
NOTICE:  BL1: Booting BL2
NOTICE:  BL2: v1.1(release):be3e473
NOTICE:  BL2: Built : 16:21:15, Apr  3 2015
ERROR:   Failed to load BL3-0 (-1)
PANIC at PC : 0x00000000f98194b0
```

**Comment by koenkooi** [comment]
I get the same bug without the 800MHz patch, so ignore the above. See https://github.com/96boards/bugs/issues/38

**Comment by hzhuang1** [comment]
The issue that you reported is fixed just now. Please notice pull request #23.

**Comment by koenkooi** [comment]
Yes, everything works as expected now. I think the 800MHz change is ready to get merged.

**Comment by hzhuang1** [comment]
This commit can't work well on some boards. Now a new patch set is merged for fixing the issue. https://github.com/96boards/arm-trusted-firmware/pull/34

**Pull request closed without merging**
