### PR TITLE
Hikey DDR 800mhz support

### PR DESCRIPTION
**Pull request by koenkooi**
Make DDR working in 800MHz by default.

Signed-off-by: Haojian Zhuang haojian.zhuang@linaro.org

### CODE REVIEW

**Comment by koenkooi** [comment]
The bootrom has trouble loading it, I keep getting:

sudo python hisi-idt.py --img1=l-loader.bin
+----------------------+
 Serial:  /dev/serial/by-id/usb-䕇䕎䥎_㄰㌲㔴㜶㤸-if00-port0
 Image1:  l-loader.bin
 Image2:
+----------------------+

Sending l-loader.bin ...
failed
Done

**Comment by hzhuang1** [comment]
Could you help to capture the log on debug console?

**Comment by koenkooi** [comment]
OK, my problem above was due to using 'master' and not the 'hikey-v2.2.0' tag in l-loader. I've flashed it and it seems to work. Is there a quick way I can check it at runtime in linux if it's using the ddr800 timings?

**Comment by hzhuang1** [comment]
ATF will dump DDR800Mhz on the debug UART.

**Comment by koenkooi** [comment]
OK, so I'm not using the right one:

NOTICE:  BL1: v1.1(release):9a97502^M
NOTICE:  BL1: Built : 08:13:36, Mar 10 2015^M
NOTICE:  succeed to init lpddr3 rank0 dram phy^M
INFO:    lpddr3_freq_init, set ddrc 533mhz^M
INFO:    init ddr3 rank0 in 533MHz^M
INFO:    ddr3 rank1 init pass in 533MHz^M
INFO:    Elpida DDR^M

**Comment by koenkooi** [comment]
```
[koen@thinkpad hisi-idt]$ ./flash.sh
+ sudo python hisi-idt.py --img1=l-loader.bin
+----------------------+
 Serial:  /dev/serial/by-id/usb-䕇䕎䥎_㄰㌲㔴㜶㤸-if00-port0
 Image1:  l-loader.bin
 Image2:
+----------------------+

Sending l-loader.bin ...
Done

+ sudo fastboot flash ptable ptable.img
< waiting for device >
```

This hangs and on the debug uart I get:

```
reset device done.
start enum.
enum done intr
Enum is starting.
usb reset intr
enum done intr
NULL package
NULL package
USB ENUM OK.
init ser device done....
USB:: Err!! Unknown USB setup packet!
NULL package
USB:: Err!! Unknown USB setup packet!
NULL package
uFileAddress=ss=f9800800

Switch to aarch64 mode. CPU0 executes at 0xf9801000!
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(release):94b2642
NOTICE:  BL1: Built : 15:34:20, Mar 17 2015
INFO:    lpddr3_freq_init, set ddrc 800mhz
INFO:    init ddr3 rank0
INFO:    ddr3 rank1 init pass
INFO:    Elpida DDR
00000000f20003e800000000f20003e800000000f20003e8 
```

It will keep writing '00000000f20003e8'

**Comment by koenkooi** [comment]
And after a power cycle I get:

```
debug EMMC boot: print init OK^M^M
debug EMMC boot: send RST_N .^M^M
debug EMMC boot: start eMMC boot......^M^M
load fastboot1!^M^M

^MSwitch to aarch64 mode. CPU0 executes at 0xf9801000!
^MNOTICE:  Booting Trusted Firmware^M
NOTICE:  BL1: v1.1(release):9a97502^M
NOTICE:  BL1: Built : 08:13:36, Mar 10 2015^M
NOTICE:  succeed to init lpddr3 rank0 dram phy^M
INFO:    lpddr3_freq_init, set ddrc 533mhz^M
INFO:    init ddr3 rank0 in 533MHz^M
INFO:    ddr3 rank1 init pass in 533MHz^M
INFO:    Elpida DDR^M
NOTICE:  BL1: Booting BL2^M
NOTICE:  BL2: v1.1(release):ad26beb^M
NOTICE:  BL2: Built : 08:16:32, Mar 17 2015^M
NOTICE:  BL1: Booting BL3-1^M
NOTICE:  BL3-1: v1.1(release):ad26beb^M
NOTICE:  BL3-1: Built : 08:16:37, Mar 17 2015^M
```

**Comment by koenkooi** [comment]
I've finally managed to test this:

```
Switch to aarch64 mode. CPU0 executes at 0xf9801000!
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(release):f69d2d3
NOTICE:  BL1: Built : 08:07:21, Mar 20 2015
INFO:    lpddr3_freq_init, set ddrc 800mhz
INFO:    init ddr3 rank0
INFO:    ddr3 rank1 init pass
INFO:    Elpida DDR
NOTICE:  BL1: Booting BL2
NOTICE:  BL2: v1.1(release):ad26beb
NOTICE:  BL2: Built : 08:16:32, Mar 17 2015
NOTICE:  BL1: Booting BL3-1
NOTICE:  BL3-1: v1.1(release):ad26beb
NOTICE:  BL3-1: Built : 08:16:37, Mar 17 2015
```

Kernel also boots normally.

**Comment by koenkooi** [comment]
I've been running this successfully for a week now. It needs a oneline fix to apply to current git, though. @Leo-Yan does this still need all the barriers after your mmio fixes?

**Comment by Leo-Yan** [comment]
On Fri, Apr 03, 2015 at 04:53:48AM -0700, Koen Kooi wrote:

> I've been running this successfully for a week now. It needs a oneline fix to apply to current git, though. @Leo-Yan does this still need all the barriers after your mmio fixes?

For my patch for adding barriers in mmio functions, it has been merged
into ATF's hikey branch. otherwise we still see some stability issues when
Haojian and me tried to merge patches into github.

Koen, from you upper question, u mean we need remove my patch or u
suggest after apply my patch, then we don't need other dsb() code
which has been insterted into ddr init flow?

**Comment by koenkooi** [comment]
I meant to ask: After your patches that went in recently, do we still need all the barriers the ddr800 patch adds?

**Comment by koenkooi** [comment]
I rebased the commit and submitted it as #22

**Pull request closed without merging**
