### PR TITLE
hikey usb.h: fix alignment issue

### PR DESCRIPTION
**Pull request by koenkooi**
Fix bug #2 as mentioned by Jerome Forissier in https://lists.96boards.org/pipermail/dev/2015-March/000138.html

Signed-off-by: Koen Kooi koen.kooi@linaro.org;

### CODE REVIEW

**Comment by jforissier** [comment]
@koenkooi thanks for fixing this, however are you sure this is the right thing to do? What about the other packed structs? Should they be changed too? Why packing in the first place? If packing is justified, then maybe the right fix is to use `-mstrict-align`?
I am just trying to make sure the same bug won't be triggered in other circumstances.

**Comment by koenkooi** [comment]
I'm not sure at all, I only verified that it makes bl1/l-loader.bin work well enough to boot.

**Comment by daniel-thompson** [comment]
To what extent will -mstrict-align penalize code that doesn't make misaligned access? Do we really want this?

Jerome observed that the problem starts out in usb_handle_control_request when structures are initialized on the stack. I had a look at the code in question and it seems to me that is was clearly designed _not_ to initialize the structures on the stack! Instead from the variable names and the comments I believe it was supported to initialize the structures ahead of time as part or .rodata and then use memcpy().

What is odd in this code is the structures are not const'ed meaning it is OK for the compiler to try and initialize them on the stack. What happens if these structures are given proper const qualifiers?

**Comment by jforissier** [comment]
const is not enough to fix the issue, but static (or static const) does the trick. With static, the structures end up in the .data section whereas with static const they are in the ro section (as can be seen from bl1.dump).

Note that I have tested with "aarch64-linux-gnu-gcc (Ubuntu/Linaro 4.9.1-16ubuntu6) 4.9.1." (the compiler which comes with my Linux distribution).
I could not reproduce the issue with "aarch64-linux-gnu-gcc (crosstool-NG linaro-1.13.1-4.9-2014.08 - Linaro GCC 4.9-2014.08) 4.9.1 20140529 (prerelease)" (dowloaded from releases.linaro.org).

**Comment by jim-wilson** [comment]
-mstrict-align will primarily affect unaligned operations, but it will also disable some memcpy optimizations, for instance given

```
#include <string.h>
void sub4 (char *c, char *d) { memcpy (c, d, 4); }
void sub8 (char *c, char *d) { memcpy (c, d, 8); }
```

Without -mstrict-align, Aarch64 gcc will use ldr/str on w/x registers for the mempcy. With -mstrict-align, gcc will use 4 pairs of ldrb/strb for the first function, and will call memcpy for the second function.  This means structure copy may be slower, but should only use aligned load/store operations.

**Comment by jim-wilson** [comment]
Doesn't like angle brackets I guess.  That was an include string.h.

**Comment by koenkooi** [comment]
enclose the code using 3 backticks before and after like python to get the #include right. I've fixed your comment manually to make it display correctly.

**Comment by Leo-Yan** [comment]
Have created a PR: https://github.com/96boards/arm-trusted-firmware/pull/10

ATF bug tracking also has been reported this issue before: https://github.com/ARM-software/tf-issues/issues/294

Go back to check the bL1's code, it will set SCTLR to disable all un-alignment accessing, so that we need set -mstrict-align to make sure all accessing is alignment.

 62         /\* ---------------------------------------------
 63          \* Enable the instruction cache, stack pointer
 64          \* and data access alignment checks
 65          \* ---------------------------------------------
 66          */
 67         mov     x1, #(SCTLR_I_BIT | SCTLR_A_BIT | SCTLR_SA_BIT)
 68         mrs     x0, sctlr_el3
 69         orr     x0, x0, x1
 70         msr     sctlr_el3, x0
 71         isb

**Pull request merged**
